### PR TITLE
Make this project responsive for larger desktop

### PR DESCRIPTION
**Pull request by maafaishal**

### CODE REVIEW

**Comment by TinaHeiligers** [comment]
The background image for the players scores area is statically too big. Double check this.

**Comment by TinaHeiligers** [comment]
@maafaishal Thank you, this is great!
I will merge over the weekend when I have time to verify deploy.

**Comment by maafaishal** [comment]
Yup. Just ask me if this PR still has problems 👍

**Comment by maafaishal** [comment]
Oh sorry about this. I don't know if I remove my fork, you cannot merge my PR.
I will try to fork this repo again, and copy-paste from my local repo.

**Comment by TinaHeiligers** [comment]
Closing, new PR with the work is in.

**Pull request closed without merging**
